services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tarea_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3000:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "5000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - backend
